### ISSUE TITLE
Parsing json array not working

### ISSUE THREAD

**Issue by udhayakumaran** [kristopolous/TickTick#38]
Test case in 0015.iteration.test.sh is not working.

**Comment by kristopolous** [comment]
wow. alright then. look at that.

**Comment by kristopolous** [comment]
how could this have ever worked? who's running this thing? Tyler Durden? 
Let me look into it

**Comment by kristopolous** [comment]
yeah ok so that was because of this guy (https://github.com/kaos/TickTick) who wrote a fork that supported this notation.  You can use his thing or if you really want mine to work, ask me here.
